cuda-11.8 loaded successful
gcc-9.3.0 loaded successful
/home/bingxing2/home/scx8ah2/.conda/envs/LLMSeg_cp310/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/bingxing2/home/scx8ah2/.conda/envs/LLMSeg_cp310/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
{'EXP_NAME': 'resnet101_cfbi', 'DIR_ROOT': './', 'DIR_DATA': './datasets', 'DIR_DAVIS': './datasets/DAVIS', 'DIR_VOST': './datasets/VOST', 'DIR_ROVES': './datasets/ROVES', 'DIR_YTB': './datasets/YTB/train', 'DIR_YTB_EVAL': './datasets/YTB/valid', 'DIR_RESULT': './result/resnet101_cfbi', 'DIR_CKPT': './result/resnet101_cfbi/ckpt', 'DIR_LOG': './result/resnet101_cfbi/log', 'DIR_IMG_LOG': './result/resnet101_cfbi/log/img', 'DIR_TB_LOG': './result/resnet101_cfbi/log/tensorboard', 'DIR_EVALUATION': './result/resnet101_cfbi/eval', 'DATASETS': ['youtubevos'], 'DATA_WORKERS': 4, 'DATA_RANDOMCROP': (465, 465), 'DATA_RANDOMFLIP': 0.5, 'DATA_MAX_CROP_STEPS': 5, 'DATA_MIN_SCALE_FACTOR': 1.0, 'DATA_MAX_SCALE_FACTOR': 1.3, 'DATA_SHORT_EDGE_LEN': 480, 'DATA_RANDOM_REVERSE_SEQ': True, 'DATA_DAVIS_REPEAT': 30, 'DATA_CURR_SEQ_LEN': 3, 'DATA_RANDOM_GAP_DAVIS': 3, 'DATA_RANDOM_GAP_YTB': 3, 'PRETRAIN': True, 'PRETRAIN_FULL': False, 'PRETRAIN_MODEL': './pretrain_models/resnet101-deeplabv3p.pth.tar', 'MODEL_BACKBONE': 'resnet', 'MODEL_MODULE': 'networks.cfbi.cfbi', 'MODEL_OUTPUT_STRIDE': 16, 'MODEL_ASPP_OUTDIM': 256, 'MODEL_SHORTCUT_DIM': 48, 'MODEL_SEMANTIC_EMBEDDING_DIM': 100, 'MODEL_HEAD_EMBEDDING_DIM': 256, 'MODEL_PRE_HEAD_EMBEDDING_DIM': 64, 'MODEL_GN_GROUPS': 32, 'MODEL_GN_EMB_GROUPS': 25, 'MODEL_MULTI_LOCAL_DISTANCE': [2, 4, 6, 8, 10, 12], 'MODEL_LOCAL_DOWNSAMPLE': True, 'MODEL_REFINE_CHANNELS': 64, 'MODEL_LOW_LEVEL_INPLANES': 256, 'MODEL_RELATED_CHANNELS': 64, 'MODEL_EPSILON': 1e-05, 'MODEL_MATCHING_BACKGROUND': True, 'MODEL_GCT_BETA_WD': True, 'MODEL_FLOAT16_MATCHING': True, 'MODEL_FREEZE_BN': True, 'MODEL_FREEZE_BACKBONE': False, 'TRAIN_TOTAL_STEPS': 100000, 'TRAIN_START_STEP': 0, 'TRAIN_LR': 0.01, 'TRAIN_MOMENTUM': 0.9, 'TRAIN_COSINE_DECAY': False, 'TRAIN_WARM_UP_STEPS': 1000, 'TRAIN_WEIGHT_DECAY': 0.00015, 'TRAIN_POWER': 0.9, 'TRAIN_GPUS': 4, 'TRAIN_BATCH_SIZE': 8, 'TRAIN_START_SEQ_TRAINING_STEPS': 50000.0, 'TRAIN_TBLOG': False, 'TRAIN_TBLOG_STEP': 60, 'TRAIN_LOG_STEP': 20, 'TRAIN_IMG_LOG': False, 'TRAIN_TOP_K_PERCENT_PIXELS': 0.15, 'TRAIN_HARD_MINING_STEP': 50000.0, 'TRAIN_CLIP_GRAD_NORM': 5.0, 'TRAIN_SAVE_STEP': 1000, 'TRAIN_MAX_KEEP_CKPT': 8, 'TRAIN_RESUME': False, 'TRAIN_RESUME_CKPT': None, 'TRAIN_RESUME_STEP': 0, 'TRAIN_AUTO_RESUME': True, 'TRAIN_GLOBAL_ATROUS_RATE': 1, 'TRAIN_LOCAL_ATROUS_RATE': 1, 'TRAIN_LOCAL_PARALLEL': True, 'TRAIN_GLOBAL_CHUNKS': 20, 'TRAIN_DATASET_FULL_RESOLUTION': True, 'TEST_GPU_ID': 0, 'TEST_DATASET': 'roves', 'TEST_DATASET_FULL_RESOLUTION': False, 'TEST_DATASET_SPLIT': ['val'], 'TEST_CKPT_PATH': './pretrain_models/resnet101_cfbi.pth', 'TEST_CKPT_STEP': None, 'TEST_FLIP': False, 'TEST_MULTISCALE': [1.0], 'TEST_MIN_SIZE': None, 'TEST_MAX_SIZE': 1040.0, 'TEST_WORKERS': 4, 'TEST_GLOBAL_CHUNKS': 4, 'TEST_GLOBAL_ATROUS_RATE': 2, 'TEST_LOCAL_ATROUS_RATE': 1, 'TEST_LOCAL_PARALLEL': True, 'DIST_ENABLE': True, 'DIST_BACKEND': 'gloo', 'DIST_URL': 'file://./sharefile', 'DIST_START_GPU': 0}
Use GPU 0 for evaluating
Build backbone.
Use frozen BN in DeepLab!
Build VOS model.
Load checkpoint from ./pretrain_models/resnet101_cfbi.pth
Process dataset...
Eval resnet101_cfbi on roves:
Done!
0 :  321
1 :  910
2 :  320
3 :  330
4 :  151
5 :  93
6 :  480
7 :  390
8 :  485
9 :  365
10 :  197
11 :  110
12 :  360
13 :  337
14 :  232
15 :  111
16 :  321
17 :  190
18 :  326
19 :  328
20 :  330
21 :  359
22 :  812
Traceback (most recent call last):
  File "/home/bingxing2/home/scx8ah2/jiaxin/DeformVOS/methods/CFBI/tools/eval_net.py", line 72, in <module>
    main()
  File "/home/bingxing2/home/scx8ah2/jiaxin/DeformVOS/methods/CFBI/tools/eval_net.py", line 69, in main
    evaluator.evaluating()
  File "/home/bingxing2/home/scx8ah2/jiaxin/DeformVOS/methods/CFBI/./networks/engine/eval_manager.py", line 159, in evaluating
    for seq_idx, seq_dataset in enumerate(self.dataset):
  File "/home/bingxing2/home/scx8ah2/jiaxin/DeformVOS/methods/CFBI/./dataloaders/datasets.py", line 303, in __getitem__
    images = list( filter(lambda x: x.endswith(".jpg"), os.listdir( image_root)  )) 
NotADirectoryError: [Errno 20] Not a directory: './datasets/ROVES/Annotations/chanlleng_label.json/images'
